theme: jekyll-theme-minimal
title: [Nabil Imam]
logo: 
description: [I work on topics in machine learning and theoretical neuroscience with the goal of understanding general principles of neural coding and computation and their technological applications]
show_downloads: false
google_analytics: []
